### PR TITLE
Add CollegeVine

### PR DESCRIPTION
**Pull request by gasi**
We build the majority of our UIs in PureScript using our own [purescript-elmish](https://pursuit.purescript.org/packages/purescript-elmish) framework (PureScript + Elm Architecture + React).

### CODE REVIEW

**Comment by ajnsit** [comment]
Thanks!

**Comment by ajnsit** [comment]
@gasi Though I wonder why you didn't use one of the existing Purescript UI libraries that use Elm architecture - say [Spork](https://github.com/natefaubion/purescript-spork) or [Hedwig](https://github.com/utkarshkukreti/purescript-hedwig)?

**Comment by gasi** [comment]
> @ajnsit Though I wonder why you didn't use one of the existing Purescript UI libraries that use Elm architecture - say [Spork](https://github.com/natefaubion/purescript-spork) or [Hedwig](https://github.com/utkarshkukreti/purescript-hedwig)?

Great question! We plan to talk about this more in the future, but in short: Our original staffing required us to use React/JSX for rendering UI. Choosing React also allows us to tap into the vast ecosystem of community components when needed: https://github.com/brillout/awesome-react-components.

Personally, I find adopting custom Virtual DOM implementations has unnecessarily isolated the PureScript ecosystem even more, for arguably marginal gains. I can imagine similar considerations influenced Lumi’s choice to build on top of React:

 - https://www.lumi.dev/blog/announcing-lumi-components
- https://github.com/lumihq/purescript-react-basic/

**Comment by ajnsit** [comment]
@gasi Thanks for the answer. I'm glad we are spoilt for choice when it comes to Purescript UI libraries!

In case you haven't seen it already, can I also plug my own UI lib - [Concur](https://github.com/ajnsit/purescript-concur)? It also has a React backend, and is strictly more powerful than the Elm Architecture while also being simpler and easier to use. You might find the [comparison with Elm Architecture](https://github.com/ajnsit/concur-documentation#replicating-elm-architecture) interesting.

**Pull request merged**
